org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft / NeoForge
minecraft_version=1.21.1
neo_version=21.1.172

# Mod
mod_id=argentinaflags
mod_name=Argentina Flags
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.argentinaflags
